export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="gallois"

export EDITOR=/usr/bin/vim
export TERM=xterm-256color
export LC_CTYPE=en_GB.UTF-8

plugins=(git)
source $ZSH/oh-my-zsh.sh

# Java / Torquebox / JRuby
export JAVA_HOME=`/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java_home`
export ECLIPSE_HOME=/Applications/eclipse

export PATH=~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/usr/local/mysql/bin:/opt/local/bin:/opt/local/sbin:/Users/kris/.rvm/bin:$JRUBY_HOME/bin

# fix rvm with zsh
unsetopt auto_name_dirs

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"  

# Allow rvm to work with iTerm2
__rvm_project_rvmrc
# Enable RVM cd functionality
export rvm_project_rvmrc=1

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

# path to gem executables for system Ruby
PATH=/usr/local/Cellar/ruby/1.9.3-p194/bin:$PATH

# Run an ClamAV scan on Downloads
alias avdown="freshclam --quiet; clamscan -r -i ~/Downloads | grep Infected"

# Set correct term for tmux so solarized theme works in vim
alias tmux="TERM=screen-256color-bce tmux"
# old skool BASIC style
alias cls='clear'

# Builtin aliases
# make grep case insensitive
alias grep="grep -i"

# Rails aliases
alias rs="rspec spec"
alias cuke="cucumber features"
alias rr="rake routes"
alias rrg="rake routes | grep"
alias rtg="rake -T | grep"
alias bi="export LC_CTYPE=en_GB.UTF-8; bundle install"
alias be="bundle exec"
alias rdbm="rake db:migrate"
alias rdbtp="rake db:test:prepare"
alias td="tail -f log/development.log"

# Git aliases
alias gb="git checkout -b"
alias gst="git status -sb"
alias gcl='git branch --merged | grep -v "\*" | xargs -n 1 git branch -d'
alias gpo="git pull origin"

# Browser aliases
alias 8080="open http://localhost:8080"
alias 8082="open http://localhost:8082"
alias 3000="open http://localhost:3000"
alias 9000="open http://localhost:9000"

# postrgres

alias start_postgres="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start"

# prevent zsh: no matches found
alias rake='noglob rake'

# Project aliases
source ~/.zshrc.projects

# Tokens and the like
source ~/.zshrc.private

# Set vi mode, ESC will allow hjkl movements
set -o vi

# https://github.com/clvv/fasd
# eval "$(fasd --init auto)"

# Ctrl+R searches history
bindkey '^R' history-incremental-search-backward
